# illnesses_data = {
#   "scale rot": "Scale rot is a bacterial infection that affects reptiles, particularly snakes and lizards. It is typically caused by unsanitary living conditions and can result in lesions, ulcers, and the deterioration of the scales. Proper hygiene, habitat maintenance, and prompt veterinary care are crucial for prevention and treatment.",
#   "respiratory infection": "Respiratory infections are illnesses that affect the respiratory system, including the lungs and airways. These infections can be caused by bacteria, viruses, or fungi, and symptoms often include coughing, sneezing, difficulty breathing, and nasal discharge. Treatment depends on the underlying cause and may include antibiotics, antivirals, or antifungal medications, along with supportive care.",
#   "avian flu": "Avian flu, also known as avian influenza, is a viral infection that primarily affects birds but can also infect humans and other animals. The virus is highly contagious among birds and can cause severe respiratory illness and high mortality rates in poultry. Human infections, though rare, can occur and may lead to severe respiratory symptoms. Control measures include culling infected birds, vaccination programs, and strict biosecurity practices."
# }

illnesses_data = {
    "scale rot": {
        "description": "Scale rot is a bacterial infection that affects reptiles, particularly snakes and lizards. It is typically caused by unsanitary living conditions and can result in lesions, ulcers, and the deterioration of the scales. Proper hygiene, habitat maintenance, and prompt veterinary care are crucial for prevention and treatment.",
        "remedies": "To treat scale rot, ensure the enclosure is kept clean and dry to prevent further infection. Use appropriate substrate that does not retain moisture, and monitor humidity levels and temperature gradients carefully. Additionally, ensure the reptile has consistent access to clean water and a balanced diet to support its immune function and aid in recovery from the illness. Enrofloxacin (Baytril) and ceftazidime (Fortaz) are systemic antibiotics commonly used for treating scale rot. These antibiotics should only be administered under the guidance and prescription of a qualified veterinarian. Consult your vet to determine the appropriate dosage and administration method for your pet's condition."
    },
    "respiratory infection": {
        "description": "Respiratory infections are illnesses that affect the respiratory system, including the lungs and airways. These infections can be caused by bacteria, viruses, or fungi, and symptoms often include coughing, sneezing, difficulty breathing, and nasal discharge. Treatment depends on the underlying cause and may include antibiotics, antivirals, or antifungal medications, along with supportive care.",
        "remedies": "To manage respiratory infections, it's essential to maintain a clean and well-ventilated living area to minimize the spread of infection. Provide warm and humid conditions to alleviate respiratory discomfort, and ensure the mammal stays hydrated with access to clean water. Monitoring and maintaining proper nutrition are crucial to support the immune system and aid in recovery. Amoxicillin, doxycycline, and enrofloxacin (Baytril) are antibiotics commonly used to treat respiratory infections in mammals. These antibiotics should only be administered under the guidance and prescription of a qualified veterinarian. Consult your vet to determine the appropriate dosage and administration method for your pet's condition."
    },
    "avian flu": {
        "description": "Avian flu, also known as avian influenza, is a viral infection that primarily affects birds but can also infect humans and other animals. The virus is highly contagious among birds and can cause severe respiratory illness and high mortality rates in poultry. Human infections, though rare, can occur and may lead to severe respiratory symptoms. Control measures include culling infected birds, vaccination programs, and strict biosecurity practices.",
        "remedies": "To manage avian flu, it's crucial to maintain their warmth, hydration, and stress levels. Ensure the bird has easy access to food and water to support its recovery. Implementing strict biosecurity measures is essential to prevent the spread of the virus to other birds. These measures are vital for managing avian flu effectively and minimizing its impact on bird populations. Treatment primarily focuses on supportive care, biosecurity measures, and vaccination when available."
    },
    #THIS ILLNESS NEEDS TO BE ADDED TO THE DATABASE
    # "psittacosis": {
    #     "description": "Psittacosis is treated primarily with antibiotics like doxycycline. In the absence of medication, supportive care and hygiene are crucial.",
    #     "remedies": "To manage psittacosis, it's essential to isolate the infected bird to prevent the spread of the infection to other birds. Maintain a clean and hygienic environment to reduce the risk of further infection. Provide supportive care such as fluids and proper nutrition to aid in the bird's recovery. Doxycycline is an antibiotic commonly used to treat psittacosis in birds. This antibiotic should only be administered under the guidance and prescription of a qualified veterinarian. Consult your vet to determine the appropriate dosage and administration method for your pet's condition."
    # }
}