"""illnessesmedications table created

Revision ID: 081b16711afb
Revises: 8e486286a437
Create Date: 2024-06-21 18:57:02.613139

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '081b16711afb'
down_revision = '8e486286a437'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('illnessesMedications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('illness_id', sa.Integer(), nullable=True),
    sa.Column('medication_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['illness_id'], ['illnesses.id'], name=op.f('fk_illnessesMedications_illness_id_illnesses')),
    sa.ForeignKeyConstraint(['medication_id'], ['medications.id'], name=op.f('fk_illnessesMedications_medication_id_medications')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('illnessesMedications')
    # ### end Alembic commands ###
