"""create illnessesclassification table

Revision ID: 0a75e2a54be2
Revises: ec4f7976952e
Create Date: 2024-06-15 22:04:56.944768

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a75e2a54be2'
down_revision = 'ec4f7976952e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('illnessesclassifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('illness_id', sa.Integer(), nullable=True),
    sa.Column('classification_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['classification_id'], ['classifications.id'], name=op.f('fk_illnessesclassifications_classification_id_classifications')),
    sa.ForeignKeyConstraint(['illness_id'], ['illnesses.id'], name=op.f('fk_illnessesclassifications_illness_id_illnesses')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('illnessesclassifications')
    # ### end Alembic commands ###
