"""illnessesmedications table created with fixed name

Revision ID: 37209673980c
Revises: 081b16711afb
Create Date: 2024-06-21 18:59:40.285290

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37209673980c'
down_revision = '081b16711afb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('illnessesmedications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('illness_id', sa.Integer(), nullable=True),
    sa.Column('medication_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['illness_id'], ['illnesses.id'], name=op.f('fk_illnessesmedications_illness_id_illnesses')),
    sa.ForeignKeyConstraint(['medication_id'], ['medications.id'], name=op.f('fk_illnessesmedications_medication_id_medications')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('illnessesmedications')
    # ### end Alembic commands ###
