"""add species_type column to pets table

Revision ID: 43116c6769e3
Revises: 0a75e2a54be2
Create Date: 2024-06-16 15:28:56.615062

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43116c6769e3'
down_revision = '0a75e2a54be2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('species_type', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pets', schema=None) as batch_op:
        batch_op.drop_column('species_type')

    # ### end Alembic commands ###
