"""removed remedies column from illnesses table

Revision ID: 4beeda5f2ae8
Revises: dbab60ee122b
Create Date: 2024-10-29 18:48:09.253229

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4beeda5f2ae8'
down_revision = 'dbab60ee122b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('illnesses', schema=None) as batch_op:
        batch_op.drop_column('remedy')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('illnesses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('remedy', sa.VARCHAR(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
