"""illnessesremedies table created

Revision ID: 4f07b44fccc6
Revises: 4beeda5f2ae8
Create Date: 2024-10-29 19:12:32.021942

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f07b44fccc6'
down_revision = '4beeda5f2ae8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('illnessesremedies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('illness_id', sa.Integer(), nullable=False),
    sa.Column('remedy', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['illness_id'], ['illnesses.id'], name=op.f('fk_illnessesremedies_illness_id_illnesses')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('illnessesremedies')
    # ### end Alembic commands ###
