"""changed remedies column to remedy in illness table

Revision ID: 7c3d6c90a284
Revises: 0705a8bab7f7
Create Date: 2024-06-21 12:37:47.656475

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c3d6c90a284'
down_revision = '0705a8bab7f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('illnesses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('remedy', sa.String(), nullable=False))
        batch_op.drop_column('remedies')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('illnesses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('remedies', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.drop_column('remedy')

    # ### end Alembic commands ###
