"""change remedies column to remedies in illnesses table

Revision ID: 8e486286a437
Revises: f1b67c8795a9
Create Date: 2024-06-21 12:48:35.176175

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e486286a437'
down_revision = 'f1b67c8795a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('illnesses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('remedy', sa.String(), nullable=True))
        batch_op.drop_column('remedies')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('illnesses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('remedies', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.drop_column('remedy')

    # ### end Alembic commands ###
