"""add nullable field to illnessesmedications table

Revision ID: 9a70c610c424
Revises: 38db1a7f2aa5
Create Date: 2024-08-05 07:32:29.021440

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a70c610c424'
down_revision = '38db1a7f2aa5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('illnessesmedications', schema=None) as batch_op:
        batch_op.alter_column('illness_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('medication_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('illnessesmedications', schema=None) as batch_op:
        batch_op.alter_column('medication_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('illness_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
