"""add description column to illnesses table

Revision ID: 9e0830112208
Revises: ea899951f0b0
Create Date: 2024-06-16 17:52:06.968287

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e0830112208'
down_revision = 'ea899951f0b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('illnesses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('illnesses', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
