"""create symptomsclassifications table

Revision ID: bc25d3373a96
Revises: b236837eac55
Create Date: 2024-05-23 22:06:38.821184

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc25d3373a96'
down_revision = 'b236837eac55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('symptomsclassifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('classification_id', sa.Integer(), nullable=True),
    sa.Column('symptoms_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['classification_id'], ['classifications.id'], name=op.f('fk_symptomsclassifications_classification_id_classifications')),
    sa.ForeignKeyConstraint(['symptoms_id'], ['symptoms.id'], name=op.f('fk_symptomsclassifications_symptoms_id_symptoms')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('symptomsclassifications')
    # ### end Alembic commands ###
