"""remedies column added to illness table

Revision ID: e7f07af1b436
Revises: 2e7d0126c138
Create Date: 2024-06-20 16:47:21.078052

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7f07af1b436'
down_revision = '2e7d0126c138'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('illnesses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('remedies', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('illnesses', schema=None) as batch_op:
        batch_op.drop_column('remedies')

    # ### end Alembic commands ###
