"""create usersspecies table

Revision ID: e8c8b650766e
Revises: f0f9e4d69cb9
Create Date: 2024-05-19 21:16:52.040924

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8c8b650766e'
down_revision = 'f0f9e4d69cb9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usersspecies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Integer(), nullable=False),
    sa.Column('species_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['species_id'], ['species.id'], name=op.f('fk_usersspecies_species_id_species')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_usersspecies_user_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usersspecies')
    # ### end Alembic commands ###
