"""remove species_type column in pets table

Revision ID: ea899951f0b0
Revises: 43116c6769e3
Create Date: 2024-06-16 15:35:06.524546

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea899951f0b0'
down_revision = '43116c6769e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pets', schema=None) as batch_op:
        batch_op.drop_column('species_type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('species_type', sa.VARCHAR(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
