"""create speciesclassifications table

Revision ID: f0f9e4d69cb9
Revises: 69fee0be1127
Create Date: 2024-05-19 19:11:16.020105

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0f9e4d69cb9'
down_revision = '69fee0be1127'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('speciesclassifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('classification_id', sa.Integer(), nullable=True),
    sa.Column('species_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['classification_id'], ['classifications.id'], name=op.f('fk_speciesclassifications_classification_id_classifications')),
    sa.ForeignKeyConstraint(['species_id'], ['species.id'], name=op.f('fk_speciesclassifications_species_id_species')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('speciesclassifications')
    # ### end Alembic commands ###
