"""change remedies column to remedies in illnesses table

Revision ID: f1b67c8795a9
Revises: 7c3d6c90a284
Create Date: 2024-06-21 12:47:18.239731

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1b67c8795a9'
down_revision = '7c3d6c90a284'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('illnesses', schema=None) as batch_op:
        batch_op.alter_column('remedies',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('illnesses', schema=None) as batch_op:
        batch_op.alter_column('remedies',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###
