"""add nullable to illnessessymptoms table attribute

Revision ID: f972285a3221
Revises: cc2e81397b6f
Create Date: 2024-08-04 14:51:36.994197

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f972285a3221'
down_revision = 'cc2e81397b6f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('illnessessymptoms', schema=None) as batch_op:
        batch_op.alter_column('illness_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('symptom_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('illnessessymptoms', schema=None) as batch_op:
        batch_op.alter_column('symptom_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('illness_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
