"""species type_name nullable false

Revision ID: ff4ccdb91652
Revises: c43867584ce4
Create Date: 2024-05-26 19:21:44.560675

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff4ccdb91652'
down_revision = 'c43867584ce4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('species', schema=None) as batch_op:
        batch_op.alter_column('type_name',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('species', schema=None) as batch_op:
        batch_op.alter_column('type_name',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###
